import type { LucideIcon } from 'lucide-react';
import {
  Apple,
  Backpack,
  BadgeCheck,
  BadgeDollarSign,
  Baby,
  Banknote,
  BanknoteArrowDown,
  Banana,
  Bath,
  Beef,
  Beer,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  Bus,
  CakeSlice,
  Calculator,
  Car,
  CalendarDays,
  Camera,
  ChartCandlestick,
  ChartLine,
  ChartPie,
  Coins,
  ClipboardList,
  CreditCard,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CirclePlus,
  Clock,
  Coffee,
  Contact,
  Crown,
  Download,
  Dumbbell,
  Droplets,
  FileText,
  Flame,
  Footprints,
  Folder,
  Fuel,
  Gamepad2,
  Globe,
  Gift,
  HandCoins,
  GraduationCap,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hotel,
  Hospital,
  Image,
  KeyRound,
  Leaf,
  House,
  Landmark,
  Lightbulb,
  LibraryBig,
  MapPin,
  MessageCircle,
  Monitor,
  Package,
  PawPrint,
  Plane,
  Pencil,
  Phone,
  PiggyBank,
  Receipt,
  ShoppingBasket,
  ShoppingCart,
  Shirt,
  Sparkles,
  ReceiptText,
  Rocket,
  School,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Star,
  Store,
  Tag,
  Target,
  Ticket,
  TrainFront,
  TreePine,
  ToyBrick,
  Trash2,
  TrendingUp,
  Utensils,
  Umbrella,
  Wallet,
  WalletCards,
  Wifi,
  Users,
  Venus,
  Bell,
  Calendar,
  ChartNoAxesCombined,
} from 'lucide-react';
import { normalizeText } from './domain';

type CatalogIconOption = {
  key: string;
  label: string;
  keywords: string[];
  Icon: LucideIcon;
};

export const catalogIconOptions = [
  { key: 'house', label: 'House', keywords: ['nhà cửa', 'gia đình', 'sinh hoạt', 'home'], Icon: House },
  { key: 'baby', label: 'Baby', keywords: ['con cái', 'thai sản', 'trẻ em', 'baby'], Icon: Baby },
  { key: 'venus', label: 'Venus', keywords: ['phụ nữ', 'nữ', 'women', 'female', 'feminine', 'woman', 'girl'], Icon: Venus },
  { key: 'plane', label: 'Plane', keywords: ['du lịch', 'vé máy bay', 'travel', 'flight'], Icon: Plane },
  { key: 'heart-handshake', label: 'Heart handshake', keywords: ['hiếu hỉ', 'quan hệ', 'cưới', 'relationships'], Icon: HeartHandshake },
  { key: 'car', label: 'Car', keywords: ['xe cộ', 'ô tô', 'car', 'vehicle'], Icon: Car },
  { key: 'bike', label: 'Bike', keywords: ['xe đạp', 'đạp xe', 'bicycle'], Icon: Bike },
  { key: 'heart-pulse', label: 'Heart pulse', keywords: ['sức khỏe', 'y tế', 'health', 'medical'], Icon: HeartPulse },
  { key: 'trending-up', label: 'Trending up', keywords: ['đầu tư', 'tăng trưởng', 'investments'], Icon: TrendingUp },
  { key: 'utensils', label: 'Utensils', keywords: ['ăn uống', 'đồ ăn', 'dining', 'food'], Icon: Utensils },
  { key: 'shopping-basket', label: 'Shopping basket', keywords: ['thực phẩm', 'đi chợ', 'groceries'], Icon: ShoppingBasket },
  { key: 'lightbulb', label: 'Lightbulb', keywords: ['điện', 'đèn', 'electricity'], Icon: Lightbulb },
  { key: 'droplets', label: 'Droplets', keywords: ['nước', 'water'], Icon: Droplets },
  { key: 'wifi', label: 'Wifi', keywords: ['internet', 'wifi', 'mạng'], Icon: Wifi },
  { key: 'bus', label: 'Bus', keywords: ['di chuyển', 'xe buýt', 'transport'], Icon: Bus },
  { key: 'fuel', label: 'Fuel', keywords: ['xăng', 'nhiên liệu', 'fuel'], Icon: Fuel },
  { key: 'ticket', label: 'Ticket', keywords: ['etc', 'vé', 'urbox', 'ticket'], Icon: Ticket },
  { key: 'trash-2', label: 'Trash 2', keywords: ['tiền rác', 'rác', 'waste', 'trash'], Icon: Trash2 },
  { key: 'hotel', label: 'Hotel', keywords: ['khách sạn', 'hotel'], Icon: Hotel },
  { key: 'shirt', label: 'Shirt', keywords: ['quần áo', 'clothing'], Icon: Shirt },
  { key: 'footprints', label: 'Footprints', keywords: ['giày dép', 'shoes', 'footwear'], Icon: Footprints },
  { key: 'graduation-cap', label: 'Graduation cap', keywords: ['giáo dục', 'học tập', 'education'], Icon: GraduationCap },
  { key: 'sparkles', label: 'Sparkles', keywords: ['mỹ phẩm', 'làm đẹp', 'cosmetics', 'beauty'], Icon: Sparkles },
  { key: 'gamepad-2', label: 'Gamepad 2', keywords: ['giải trí', 'game', 'entertainment'], Icon: Gamepad2 },
  { key: 'toy-brick', label: 'Toy brick', keywords: ['đồ chơi', 'toys'], Icon: ToyBrick },
  { key: 'shopping-cart', label: 'Shopping cart', keywords: ['tiêu dùng', 'mua sắm', 'shopping'], Icon: ShoppingCart },
  { key: 'paw-print', label: 'Paw print', keywords: ['thú cưng', 'pets'], Icon: PawPrint },
  { key: 'heart', label: 'Heart', keywords: ['đám cưới', 'tình yêu', 'wedding'], Icon: Heart },
  { key: 'cake-slice', label: 'Cake slice', keywords: ['sinh nhật', 'birthday', 'cake'], Icon: CakeSlice },
  { key: 'gift', label: 'Gift', keywords: ['lì xì', 'quà tặng', 'quà', 'gifts'], Icon: Gift },
  { key: 'chart-candlestick', label: 'Chart candlestick', keywords: ['chứng khoán', 'cổ phiếu', 'stocks'], Icon: ChartCandlestick },
  { key: 'coins', label: 'Coins', keywords: ['đầu tư vàng', 'vàng', 'gold', 'coins'], Icon: Coins },
  { key: 'landmark', label: 'Landmark', keywords: ['chuyển khoản', 'ngân hàng', 'bank transfer'], Icon: Landmark },
  { key: 'credit-card', label: 'Credit card', keywords: ['thẻ tín dụng', 'credit card'], Icon: CreditCard },
  { key: 'banknote', label: 'Banknote', keywords: ['tiền mặt', 'cash', 'money'], Icon: Banknote },
  { key: 'banknote-arrow-down', label: 'Banknote arrow down', keywords: ['tiền ra', 'chi tiêu', 'rút tiền', 'expense', 'withdraw', 'spending', 'decrease'], Icon: BanknoteArrowDown },
  { key: 'circle-dollar-sign', label: 'Circle dollar sign', keywords: ['tiền', 'tài chính', 'money', 'finance', 'currency', 'dollar'], Icon: CircleDollarSign },
  { key: 'wallet', label: 'Wallet', keywords: ['ví', 'tài chính', 'wallet', 'finance'], Icon: Wallet },
  { key: 'tag', label: 'Tag', keywords: ['khác', 'chung', 'other', 'general'], Icon: Tag },
  { key: 'apple', label: 'Apple', keywords: ['trái cây', 'táo', 'apple', 'food'], Icon: Apple },
  { key: 'backpack', label: 'Backpack', keywords: ['ba lô', 'cặp sách', 'school', 'travel'], Icon: Backpack },
  { key: 'badge-check', label: 'Badge check', keywords: ['xác nhận', 'hoàn tất', 'verified'], Icon: BadgeCheck },
  { key: 'badge-dollar-sign', label: 'Badge dollar sign', keywords: ['tiền thưởng', 'tài chính', 'money', 'finance'], Icon: BadgeDollarSign },
  { key: 'banana', label: 'Banana', keywords: ['chuối', 'trái cây', 'food'], Icon: Banana },
  { key: 'bath', label: 'Bath', keywords: ['tắm', 'phòng tắm', 'bathroom'], Icon: Bath },
  { key: 'beef', label: 'Beef', keywords: ['thịt', 'thực phẩm', 'food'], Icon: Beef },
  { key: 'beer', label: 'Beer', keywords: ['bia', 'đồ uống', 'drinks'], Icon: Beer },
  { key: 'book-open', label: 'Book open', keywords: ['sách', 'đọc', 'education'], Icon: BookOpen },
  { key: 'briefcase-business', label: 'Briefcase business', keywords: ['công việc', 'business', 'work'], Icon: BriefcaseBusiness },
  { key: 'building-2', label: 'Building 2', keywords: ['tòa nhà', 'công ty', 'building'], Icon: Building2 },
  { key: 'calculator', label: 'Calculator', keywords: ['máy tính', 'tính toán', 'calculator'], Icon: Calculator },
  { key: 'calendar-days', label: 'Calendar days', keywords: ['lịch', 'ngày', 'calendar'], Icon: CalendarDays },
  { key: 'camera', label: 'Camera', keywords: ['máy ảnh', 'chụp hình', 'photo'], Icon: Camera },
  { key: 'chart-line', label: 'Chart line', keywords: ['biểu đồ', 'doanh thu', 'chart'], Icon: ChartLine },
  { key: 'chart-pie', label: 'Chart pie', keywords: ['biểu đồ tròn', 'phân tích', 'analytics'], Icon: ChartPie },
  { key: 'clipboard-list', label: 'Clipboard list', keywords: ['danh sách', 'công việc', 'list'], Icon: ClipboardList },
  { key: 'coffee', label: 'Coffee', keywords: ['cà phê', 'đồ uống', 'coffee'], Icon: Coffee },
  { key: 'contact', label: 'Contact', keywords: ['liên hệ', 'người', 'contact'], Icon: Contact },
  { key: 'crown', label: 'Crown', keywords: ['vương miện', 'cao cấp', 'premium'], Icon: Crown },
  { key: 'dumbbell', label: 'Dumbbell', keywords: ['tập gym', 'thể thao', 'fitness'], Icon: Dumbbell },
  { key: 'file-text', label: 'File text', keywords: ['hóa đơn', 'tài liệu', 'document'], Icon: FileText },
  { key: 'flame', label: 'Flame', keywords: ['nhiên liệu', 'nóng', 'fire'], Icon: Flame },
  { key: 'folder', label: 'Folder', keywords: ['thư mục', 'lưu trữ', 'folder'], Icon: Folder },
  { key: 'globe', label: 'Globe', keywords: ['du lịch', 'quốc tế', 'world'], Icon: Globe },
  { key: 'hand-coins', label: 'Hand coins', keywords: ['tiền', 'thu nhập', 'lương', 'money'], Icon: HandCoins },
  { key: 'hospital', label: 'Hospital', keywords: ['bệnh viện', 'y tế', 'health'], Icon: Hospital },
  { key: 'image', label: 'Image', keywords: ['hình ảnh', 'ảnh', 'photo'], Icon: Image },
  { key: 'key-round', label: 'Key round', keywords: ['chìa khóa', 'bảo mật', 'key'], Icon: KeyRound },
  { key: 'leaf', label: 'Leaf', keywords: ['cây xanh', 'thiên nhiên', 'nature'], Icon: Leaf },
  { key: 'library-big', label: 'Library big', keywords: ['thư viện', 'sách', 'library'], Icon: LibraryBig },
  { key: 'map-pin', label: 'Map pin', keywords: ['địa điểm', 'vị trí', 'location'], Icon: MapPin },
  { key: 'message-circle', label: 'Message circle', keywords: ['tin nhắn', 'liên lạc', 'message'], Icon: MessageCircle },
  { key: 'monitor', label: 'Monitor', keywords: ['máy tính', 'thiết bị', 'computer'], Icon: Monitor },
  { key: 'package', label: 'Package', keywords: ['gói hàng', 'bưu kiện', 'delivery'], Icon: Package },
  { key: 'phone', label: 'Phone', keywords: ['điện thoại', 'liên lạc', 'phone'], Icon: Phone },
  { key: 'piggy-bank', label: 'Piggy bank', keywords: ['heo đất', 'tiết kiệm', 'savings'], Icon: PiggyBank },
  { key: 'receipt-text', label: 'Receipt text', keywords: ['hóa đơn', 'biên lai', 'receipt'], Icon: ReceiptText },
  { key: 'rocket', label: 'Rocket', keywords: ['mục tiêu', 'khởi động', 'startup'], Icon: Rocket },
  { key: 'school', label: 'School', keywords: ['trường học', 'giáo dục', 'school'], Icon: School },
  { key: 'shopping-bag', label: 'Shopping bag', keywords: ['túi mua sắm', 'mua sắm', 'shopping'], Icon: ShoppingBag },
  { key: 'smartphone', label: 'Smartphone', keywords: ['điện thoại', 'di động', 'phone'], Icon: Smartphone },
  { key: 'star', label: 'Star', keywords: ['yêu thích', 'ưu tiên', 'favorite'], Icon: Star },
  { key: 'store', label: 'Store', keywords: ['cửa hàng', 'mua sắm', 'store'], Icon: Store },
  { key: 'target', label: 'Target', keywords: ['mục tiêu', 'kế hoạch', 'goal'], Icon: Target },
  { key: 'train-front', label: 'Train front', keywords: ['tàu hỏa', 'di chuyển', 'train'], Icon: TrainFront },
  { key: 'tree-pine', label: 'Tree pine', keywords: ['cây thông', 'thiên nhiên', 'nature'], Icon: TreePine },
  { key: 'umbrella', label: 'Umbrella', keywords: ['ô', 'mưa', 'weather'], Icon: Umbrella },
  { key: 'users', label: 'Users', keywords: ['mọi người', 'gia đình', 'people', 'family'], Icon: Users },
  { key: 'wallet-cards', label: 'Wallet cards', keywords: ['ví', 'thẻ', 'tài chính', 'wallet'], Icon: WalletCards },
  { key: 'bell', label: 'Bell', keywords: ['nhắc nhở', 'thông báo', 'reminder', 'notification'], Icon: Bell },
  { key: 'calendar', label: 'Calendar', keywords: ['lịch', 'ngày', 'calendar'], Icon: Calendar },
  { key: 'chart-no-axes-combined', label: 'Chart no axes combined', keywords: ['phân tích', 'thống kê', 'analytics'], Icon: ChartNoAxesCombined },
  { key: 'circle-alert', label: 'Circle alert', keywords: ['cảnh báo', 'lỗi', 'warning', 'alert'], Icon: CircleAlert },
  { key: 'circle-check', label: 'Circle check', keywords: ['hoàn tất', 'xác nhận', 'success', 'done'], Icon: CircleCheck },
  { key: 'circle-plus', label: 'Circle plus', keywords: ['thêm', 'tạo mới', 'add', 'plus'], Icon: CirclePlus },
  { key: 'clock', label: 'Clock', keywords: ['thời gian', 'giờ', 'time'], Icon: Clock },
  { key: 'download', label: 'Download', keywords: ['tải xuống', 'xuất', 'download', 'export'], Icon: Download },
  { key: 'pencil', label: 'Pencil', keywords: ['sửa', 'chỉnh sửa', 'edit'], Icon: Pencil },
  { key: 'receipt', label: 'Receipt', keywords: ['hóa đơn', 'biên lai', 'receipt'], Icon: Receipt },
  { key: 'shield-check', label: 'Shield check', keywords: ['bảo mật', 'an toàn', 'security'], Icon: ShieldCheck },
] as const satisfies readonly CatalogIconOption[];

export type CatalogIconKey = (typeof catalogIconOptions)[number]['key'];

const iconByKey = new Map<string, LucideIcon>(
  catalogIconOptions.map((option) => [option.key, option.Icon]),
);

const labelByKey = new Map<string, string>(
  catalogIconOptions.map((option) => [option.key, option.label]),
);

const defaultCatalogIcons: Record<string, CatalogIconKey> = {
  'Sinh hoạt gia đình': 'house',
  'Con cái': 'baby',
  'Du lịch': 'plane',
  'Hiếu hỉ & quan hệ': 'heart-handshake',
  'Nhà cửa & gia dụng': 'house',
  'Xe cộ': 'car',
  'Sức khỏe gia đình': 'heart-pulse',
  'Thai sản': 'baby',
  'Đầu tư': 'trending-up',
  'Ăn uống': 'utensils',
  'Thực phẩm': 'shopping-basket',
  'Điện': 'lightbulb',
  'Nước': 'droplets',
  Internet: 'wifi',
  'Di chuyển': 'bus',
  'Xăng': 'fuel',
  ETC: 'ticket',
  'Khách sạn': 'hotel',
  'Vé máy bay': 'plane',
  'Quần áo': 'shirt',
  'Giày dép': 'footprints',
  'Gia dụng': 'house',
  'Giáo dục': 'graduation-cap',
  'Sức khỏe': 'heart-pulse',
  'Sức khoẻ': 'heart-pulse',
  'Mỹ phẩm': 'sparkles',
  Spa: 'sparkles',
  'Giải trí': 'gamepad-2',
  'Đồ chơi': 'toy-brick',
  'Tiêu dùng': 'shopping-cart',
  'Thú cưng': 'paw-print',
  'Tiền rác': 'trash-2',
  'Đám cưới': 'heart',
  'Sinh nhật': 'cake-slice',
  'Lì xì': 'gift',
  'Sinh con': 'baby',
  Quà: 'gift',
  'Đầu tư chứng khoán': 'chart-candlestick',
  'Đầu tư vàng': 'coins',
  'Chuyển khoản': 'landmark',
  'Thẻ tín dụng': 'credit-card',
  'Trả góp': 'credit-card',
  Urbox: 'ticket',
  'Tiền mặt': 'banknote',
  'Quỹ ứng': 'wallet',
};

export function getDefaultCatalogIcon(name: string): CatalogIconKey {
  return defaultCatalogIcons[name] || 'tag';
}

export function normalizeCatalogIconKey(key: string | null | undefined): CatalogIconKey {
  return key && iconByKey.has(key) ? key as CatalogIconKey : 'tag';
}

export function getCatalogIcon(key: string | null | undefined): LucideIcon {
  return iconByKey.get(key || '') || Tag;
}

export function getCatalogIconLabel(key: string | null | undefined): string {
  return labelByKey.get(key || '') || labelByKey.get('tag') || 'Tag';
}

export function searchCatalogIcons(query: string) {
  const normalizedQuery = normalizeText(query);
  if (!normalizedQuery) return catalogIconOptions;
  return catalogIconOptions.filter((option) =>
    [option.key, option.label, ...option.keywords].some((value) =>
      normalizeText(value).includes(normalizedQuery),
    ),
  );
}
