import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
export type Language = 'vi' | 'en';
export type TranslationKey = 'overview' | 'transactions' | 'budgets' | 'catalogs' | 'members' | 'data' | 'more' | 'logout' | 'loggingOut' | 'offline' | 'reload' | 'familyLoading' | 'theme' | 'system' | 'light' | 'dark' | 'language' | 'openMenu' | 'closeMenu' | 'addTransaction' | 'month' | 'year' | 'previousMonth' | 'currentMonth' | 'dashboardError' | 'chartEmpty' | 'chartEmptyDescription' | 'viewTransactions' | 'budgetNotifications' | 'unreadBudgetNotifications' | 'unreadBudgetNotification' | 'allBudgetNotificationsRead' | 'markAllRead' | 'noBudgetNotifications' | 'you' | 'currentAccount';
const translations: Record<Language, Record<TranslationKey, string>> = { vi: { overview: 'Tổng quan', transactions: 'Giao dịch', budgets: 'Ngân sách', catalogs: 'Danh mục', members: 'Thành viên', data: 'Dữ liệu', more: 'Thêm', logout: 'Đăng xuất', loggingOut: 'Đang đăng xuất…', offline: 'Mất kết nối — dữ liệu chưa lưu sẽ không được coi là thành công.', reload: 'Thử tải lại', familyLoading: 'Đang tải dữ liệu gia đình…', theme: 'Giao diện', system: 'Theo thiết bị', light: 'Sáng', dark: 'Tối', language: 'Ngôn ngữ', openMenu: 'Mở trình đơn', closeMenu: 'Đóng trình đơn', addTransaction: 'Thêm giao dịch', month: 'Tháng', year: 'Năm', previousMonth: 'Tháng trước', currentMonth: 'Tháng này', dashboardError: 'Không thể tải dữ liệu Dashboard. Vui lòng thử lại.', chartEmpty: 'Chưa có dữ liệu biểu đồ', chartEmptyDescription: 'Biểu đồ sẽ xuất hiện khi tháng này có giao dịch thực tế.', viewTransactions: 'Xem giao dịch', budgetNotifications: 'Thông báo ngân sách', unreadBudgetNotifications: 'chưa đọc', unreadBudgetNotification: 'Chưa đọc', allBudgetNotificationsRead: 'Bạn đã xem hết thông báo.', markAllRead: 'Đánh dấu đã đọc', noBudgetNotifications: 'Chưa có cảnh báo ngân sách.', you: 'Bạn', currentAccount: 'tài khoản đang đăng nhập' }, en: { overview: 'Overview', transactions: 'Transactions', budgets: 'Budgets', catalogs: 'Categories', members: 'Members', data: 'Data', more: 'More', logout: 'Log out', loggingOut: 'Logging out…', offline: 'Offline — unsaved data is not considered saved.', reload: 'Try again', familyLoading: 'Loading family data…', theme: 'Appearance', system: 'System', light: 'Light', dark: 'Dark', language: 'Language', openMenu: 'Open menu', closeMenu: 'Close menu', addTransaction: 'Add transaction', month: 'Month', year: 'Year', previousMonth: 'Previous month', currentMonth: 'This month', dashboardError: 'Could not load dashboard data. Please try again.', chartEmpty: 'No chart data', chartEmptyDescription: 'The chart will appear when this month has actual transactions.', viewTransactions: 'View transactions', budgetNotifications: 'Budget notifications', unreadBudgetNotifications: 'unread', unreadBudgetNotification: 'Unread', allBudgetNotificationsRead: 'You are all caught up.', markAllRead: 'Mark all read', noBudgetNotifications: 'No budget alerts.', you: 'You', currentAccount: 'current account' } };
const STORAGE_KEY = 'family-expense-language';
const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void } | null>(null);
export function LanguageProvider({ children }: { children: ReactNode }) { const [language, setLanguage] = useState<Language>(() => window.localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'vi'); useEffect(() => { window.localStorage.setItem(STORAGE_KEY, language); document.documentElement.lang = language; }, [language]); return <LanguageContext.Provider value={useMemo(() => ({ language, setLanguage }), [language])}>{children}</LanguageContext.Provider>; }
export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error('useLanguage must be used inside LanguageProvider'); return { ...value, t: (key: TranslationKey) => translations[value.language][key] }; }
export function useOptionalLanguage() { const value = useContext(LanguageContext); if (value) return { ...value, t: (key: TranslationKey) => translations[value.language][key] }; return { language: 'vi' as Language, setLanguage: () => undefined, t: (key: TranslationKey) => translations.vi[key] }; }
