import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
export type Language = 'vi' | 'en';
export type TranslationKey = 'overview' | 'transactions' | 'catalogs' | 'members' | 'data' | 'logout' | 'loggingOut' | 'offline' | 'reload' | 'familyLoading' | 'theme' | 'system' | 'light' | 'dark' | 'language';
const translations: Record<Language, Record<TranslationKey, string>> = { vi: { overview: 'Tổng quan', transactions: 'Giao dịch', catalogs: 'Danh mục', members: 'Thành viên', data: 'Quản lý dữ liệu', logout: 'Đăng xuất', loggingOut: 'Đang đăng xuất…', offline: 'Mất kết nối — dữ liệu chưa lưu sẽ không được coi là thành công.', reload: 'Thử tải lại', familyLoading: 'Đang tải dữ liệu gia đình…', theme: 'Giao diện', system: 'Theo thiết bị', light: 'Sáng', dark: 'Tối', language: 'Ngôn ngữ' }, en: { overview: 'Overview', transactions: 'Transactions', catalogs: 'Categories', members: 'Members', data: 'Data management', logout: 'Log out', loggingOut: 'Logging out…', offline: 'Offline — unsaved data is not considered saved.', reload: 'Try again', familyLoading: 'Loading family data…', theme: 'Appearance', system: 'System', light: 'Light', dark: 'Dark', language: 'Language' } };
const STORAGE_KEY = 'family-expense-language';
const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void } | null>(null);
export function LanguageProvider({ children }: { children: ReactNode }) { const [language, setLanguage] = useState<Language>(() => window.localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'vi'); useEffect(() => { window.localStorage.setItem(STORAGE_KEY, language); document.documentElement.lang = language; }, [language]); return <LanguageContext.Provider value={useMemo(() => ({ language, setLanguage }), [language])}>{children}</LanguageContext.Provider>; }
export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error('useLanguage must be used inside LanguageProvider'); return { ...value, t: (key: TranslationKey) => translations[value.language][key] }; }
export function useOptionalLanguage() { const value = useContext(LanguageContext); if (value) return { ...value, t: (key: TranslationKey) => translations[value.language][key] }; return { language: 'vi' as Language, setLanguage: () => undefined, t: (key: TranslationKey) => translations.vi[key] }; }
