create extension if not exists pgcrypto;
create type public.family_role as enum ('owner','member');
create type public.member_status as enum ('active','invited','disabled');
create type public.transaction_kind as enum ('Chi tiêu','Hoàn tiền','Thu nhập','Tạm ứng');
create type public.transaction_status as enum ('Thực tế','Dự kiến');
create type public.transaction_source as enum ('manual','ai','excel_import');

create table public.families(id uuid primary key default gen_random_uuid(),name text not null,currency text not null default 'VND',timezone text not null default 'Asia/Ho_Chi_Minh',created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.family_members(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,display_name text not null,role family_role not null default 'member',status member_status not null default 'active',created_at timestamptz not null default now(),unique(family_id,user_id));
create table public.purposes(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,code text not null,color text,icon text,sort_order int not null default 0,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(family_id,code));
create table public.expense_types(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,code text not null,sort_order int not null default 0,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(family_id,code));
create table public.purpose_expense_type_suggestions(purpose_id uuid not null references public.purposes(id) on delete cascade,expense_type_id uuid not null references public.expense_types(id) on delete cascade,priority int not null default 0,primary key(purpose_id,expense_type_id));
create table public.payment_methods(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,active boolean not null default true,sort_order int not null default 0,unique(family_id,name));
create table public.accounts(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,account_type text,institution text,last_four_digits text check(last_four_digits is null or last_four_digits ~ '^\d{4}$'),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.events(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,event_type text,start_date date,end_date date,budget numeric(15,0) check(budget is null or budget>=0),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or start_date is null or end_date>=start_date));
create table public.beneficiaries(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(family_id,name));
create table public.transactions(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,transaction_date date not null,transaction_type transaction_kind not null,status transaction_status not null,description text not null check(length(trim(description))>0),amount numeric(15,0) not null check(amount>0),purpose_id uuid not null references public.purposes(id),expense_type_id uuid not null references public.expense_types(id),event_id uuid references public.events(id),beneficiary_id uuid references public.beneficiaries(id),payment_method_id uuid references public.payment_methods(id),account_id uuid references public.accounts(id),note text,created_by uuid not null references auth.users(id),updated_by uuid not null references auth.users(id),source transaction_source not null default 'manual',source_reference text,ai_generated boolean not null default false,ai_confidence numeric(3,2) check(ai_confidence between 0 and 1),ai_original_input text,ai_suggested_values jsonb,ai_model text,ai_confirmed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,unique(family_id,source,source_reference));
create table public.budgets(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,year int not null check(year between 2000 and 2200),month int not null check(month between 1 and 12),purpose_id uuid not null references public.purposes(id),amount numeric(15,0) not null check(amount>=0),warning_threshold numeric(4,3) not null default .8 check(warning_threshold>0 and warning_threshold<=1),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(family_id,year,month,purpose_id));
create table public.recurring_transactions(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,template jsonb not null,frequency text not null,next_run_date date,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.ai_usage_logs(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,user_id uuid not null references auth.users(id),request_date date not null default current_date,model text not null,status text not null,latency_ms int,input_length int,error_code text,created_at timestamptz not null default now());
create index transactions_family_date_idx on public.transactions(family_id,transaction_date desc) where deleted_at is null;
create index transactions_duplicate_idx on public.transactions(family_id,transaction_date,amount) where deleted_at is null;
create index ai_usage_rate_idx on public.ai_usage_logs(user_id,created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql security invoker set search_path='' as $$begin new.updated_at=now();return new;end$$;
create trigger families_touch before update on public.families for each row execute function public.touch_updated_at();
create trigger transactions_touch before update on public.transactions for each row execute function public.touch_updated_at();
create trigger budgets_touch before update on public.budgets for each row execute function public.touch_updated_at();

create or replace function public.is_family_member(fid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.family_members m where m.family_id=fid and m.user_id=auth.uid() and m.status='active')$$;
create or replace function public.is_family_owner(fid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.family_members m where m.family_id=fid and m.user_id=auth.uid() and m.role='owner' and m.status='active')$$;
revoke all on function public.is_family_member(uuid) from public;revoke all on function public.is_family_owner(uuid) from public;grant execute on function public.is_family_member(uuid),public.is_family_owner(uuid) to authenticated,service_role;

alter table public.families enable row level security;alter table public.family_members enable row level security;alter table public.purposes enable row level security;alter table public.expense_types enable row level security;alter table public.purpose_expense_type_suggestions enable row level security;alter table public.payment_methods enable row level security;alter table public.accounts enable row level security;alter table public.events enable row level security;alter table public.beneficiaries enable row level security;alter table public.transactions enable row level security;alter table public.budgets enable row level security;alter table public.recurring_transactions enable row level security;alter table public.ai_usage_logs enable row level security;
create policy families_select on public.families for select to authenticated using(public.is_family_member(id));create policy families_insert on public.families for insert to authenticated with check(created_by=auth.uid());create policy families_update on public.families for update to authenticated using(public.is_family_owner(id)) with check(public.is_family_owner(id));
create policy members_select on public.family_members for select to authenticated using(public.is_family_member(family_id));create policy members_manage on public.family_members for all to authenticated using(public.is_family_owner(family_id)) with check(public.is_family_owner(family_id));
create policy members_bootstrap on public.family_members for insert to authenticated with check(user_id=auth.uid() and role='owner' and exists(select 1 from public.families f where f.id=family_id and f.created_by=auth.uid()));
do $$declare t text;begin foreach t in array array['purposes','expense_types','payment_methods','accounts','events','beneficiaries','budgets','recurring_transactions'] loop execute format('create policy %I on public.%I for select to authenticated using(public.is_family_member(family_id))',t||'_select',t);execute format('create policy %I on public.%I for all to authenticated using(public.is_family_owner(family_id)) with check(public.is_family_owner(family_id))',t||'_owner',t);end loop;end$$;
create policy transactions_select on public.transactions for select to authenticated using(public.is_family_member(family_id));create policy transactions_insert on public.transactions for insert to authenticated with check(public.is_family_member(family_id) and created_by=auth.uid() and updated_by=auth.uid());create policy transactions_update on public.transactions for update to authenticated using(public.is_family_member(family_id)) with check(public.is_family_member(family_id) and updated_by=auth.uid());
create policy suggestions_select on public.purpose_expense_type_suggestions for select to authenticated using(exists(select 1 from public.purposes p where p.id=purpose_id and public.is_family_member(p.family_id)));create policy suggestions_owner on public.purpose_expense_type_suggestions for all to authenticated using(exists(select 1 from public.purposes p where p.id=purpose_id and public.is_family_owner(p.family_id))) with check(exists(select 1 from public.purposes p where p.id=purpose_id and public.is_family_owner(p.family_id)));
create policy ai_logs_insert on public.ai_usage_logs for insert to authenticated with check(user_id=auth.uid() and public.is_family_member(family_id));create policy ai_logs_select on public.ai_usage_logs for select to authenticated using(user_id=auth.uid() and public.is_family_member(family_id));

create or replace function public.create_family(p_name text) returns uuid language plpgsql security definer set search_path='' as $$declare fid uuid;begin insert into public.families(name,created_by) values(trim(p_name),auth.uid()) returning id into fid;insert into public.family_members(family_id,user_id,display_name,role) values(fid,auth.uid(),coalesce(auth.jwt()->>'email','Chủ gia đình'),'owner');return fid;end$$;grant execute on function public.create_family(text) to authenticated;
